import './globals.css'
import type { Metadata } from 'next'
import Header from '@/components/Header'
import CategoryMenu from '@/components/CategoryMenu'
import Footer from '@/components/Footer'
import CartProvider from '@/components/cart-provider.tsx'
import Link from 'next/link'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-primaryBg">
      <body className="max-width container shadow">
      <CartProvider>
        <Header /> 
        <div className="hidden max-xl:flex">
          <Link href={`/products/search?search=`} className="text-pop flex mt-6 px-4 py-3 rounded-3xl text-lg font-bold mb-2 bg-white max-xl:hover:bg-primaryBg ">
          All products
          <Image 
            className="ml-2"
            src='/green-left-arrow.svg'
            alt='arrow'
            width={7}
            height={3}
          /> 
          </Link>
        </div>
          <CategoryMenu /> 
        {children}
      </CartProvider>
      <Footer />
      </body>
    </html>
  )
}
